baseURL = 'http://www.samskrutam.net/'
languageCode = 'en-us'
title = 'Samskrutam'
theme = 'relearn'

[params]
  themeVariant = [ "samskrutam", "blue","red", "zen-dark", "relearn-light", "relearn-dark" ]

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true